sudo: false
services:
  - docker
language: go
go:
  - 1.6.3
before_script:
  - make deps
  - make valid
script:
  - make docker
  - docker run -d -p9999:80 --name updater tompscanlan/q3updater
  - docker logs updater
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag tompscanlan/q3updater tompscanlan/q3updater:${TRAVIS_BRANCH}
  - docker push tompscanlan/q3updater:latest
  - docker push tompscanlan/q3updater:${TRAVIS_BRANCH}
